<a href="#" class="button action primary company-form-trigger">Add</a>
<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>phone number</th>
      <th>action</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($block->getCompanies() as $company): ?>
      <tr>
        <td><?= $company->getCompanyId() ?></td>
        <td><?= $company->getName() ?></td>
        <td><?= $company->getPhonenumber() ?></td>
        <td>
          <button
          data-id="<?= $company->getCompanyId() ?>"
          data-name="<?= $company->getName() ?>"
          data-phonenumber="<?= $company->getPhonenumber() ?>"
          class="button action primary company-form-trigger">Edit</button>
          <button href="#" data-id="<?= $company->getCompanyId() ?>" class="button action company-delete-trigger">Delete</button>
        </td>
      </tr>
    <?php endforeach ?>

  </tbody>
</table>

<div id="modalCompany">
    <div class="modal-body-content">
      <form action="" id="companyForm">
        <input type="hidden" name="company_id" id="company_id">
        <div class="input-group">
          <label for="name">Name</label>
          <input type="text" id="name" name="name" value="">
        </div>
        <div class="input-group">
          <label for="phonenumber">Phone Number</label>
          <input type="text" id="phonenumber" name="phonenumber" value="">
        </div>
      </form>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Hprasetyou_Company/js/masterCompany": {}
    }
}
</script>
